### ISSUE TITLE
implements PConstants is useless

### ISSUE THREAD

**Issue by clankill3r** [linux-man/VLCJVideo#2]
PImage already does that.

**Comment by linux-man** [comment]
I get it, BUT...

`public class PGraphics extends PImage implements PConstants`

`public class Movie extends PImage implements PConstants`

Everyone does it!

**Comment by linux-man** [comment]
I've been thinking about this issue and did a little investigation.
I'll stick with this "implements" because it looks like a non-written norm followed by Processing libs (and a lot others) and because of
https://stackoverflow.com/questions/5668429/why-would-both-a-parent-and-child-class-implement-the-same-interface

**Comment by clankill3r** [comment]
Processing shouldn't have implemented it in the first place but do a static import instead.
It makes the debug view so much easier to read, not it's horrible.
